### ISSUE TITLE
Refactoring Workspace JupyterHub Image

### ISSUE THREAD

**Issue by rafael-ladislau** [NYU-CI/zero-to-jupyterhub-k8s#1]
We are using as the manager of ADRF workspaces. Basically, we are leveraging the capabilities of JupyterHub / Zero to JupyterHub (z2jh) to do it. 

In the workspace deployment, we are using the version 0.9.2 of JupyterHub and 0.7.0 of Z2JH.

The JupyterHub image's DockerFile is here: https://github.com/NYU-CI/zero-to-jupyterhub-k8s/tree/adrf/images/hub

The configuration file is here:  https://github.com/NYU-CI/adrf_jupyter_helm_configuration/blob/master/staging/config-rdp.yaml

Things that need to be achieved in this refactoring:
1. The source codes inside the configuration file (config-rdp.yaml) should be migrated to the hub image. The configuration file should not have a code.
2. We should try to use the newest version of Z2JH
3. Python Boto3 lib should be installed in the requirements.txt, and when a workspace starts and finishes, an event should be published to an AWS SNS topic;
4. The List of projects should not come from LDAP, this information should come from DFAdmin
5. The amount of memory and cpu of the remote desktop and jupyterlab containers should also come from DFadmin - Projects Tools;
6. The image being used to provide JupyterLab should also come from DFadmin - Projects Tools.

**Comment by rafael-ladislau** [comment]
The name of the SNS topics are: adrf-workspace-started and adrf-workspace-stopped. They are already created in Dev and Staging.

We still need to create an IAM Role ADRFPublishToWorkspaceTopics, and add public permissions to the two Workspace SNS Topics. Ps.: Create a Policy with the same name and suffix Policy. (https://docs.aws.amazon.com/sns/latest/dg/AccessPolicyLanguage_UseCases_Sns.html)

The hub-pod should assume the Role to publish to the SNS topics using Kube2IAM (https://github.com/NYU-CI/adrf_kops_configuration/tree/master/kube2iam). The kubernetes cluster Instance Roles (Master and Nodes) should be able to assume the ADRFPublishToWorkspaceTopics. The hub pod needs to have the annotation: `iam.amazonaws.com/role: role-arn`

The published message should be a JSON with the format:
```
{
    "username": "rafael",
    "project_id": 284
}
```

**Comment by rafael-ladislau** [comment]
Boto3 Usage

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sns.html#SNS.Client.publish

https://docs.aws.amazon.com/sns/latest/api/API_Publish.html

**Comment by rafael-ladislau** [comment]
DFAdmin holds the information of Projects, Users and Datasets in the system. The dev URL is https://dfadmin.dev.adrf.cloud and the Staging URL is https://dfadmin.adrf.info (Through VPN). At the top right corner of the screen, there is a button "API". Click this button and you will be able to see the swagger view of the DFAdmin APIs. In order to achieve the goal of this issue, we will use the projects listing API. https://dfadmin.adrf.info/api/v1/projects?member=<username>
This URL will return all the projects associated with the user. And most of the configurations we will need to spin up a Workspace POD will come from the project tools field.

If you look for the user rafael for example, it will have the project "Export Test" and this project comes with following tools property: 
```
"tools": [
                {
                    "notes": null,
                    "additional_info": null,
                    "tool_name": "Workspace_K8s",
                    "other_name": "",
                    "system_info": {
  "jupyter": {
    "memory": 1000,
    "cpu": 1,
    "image": "774391758379.dkr.ecr.us-gov-west-1.amazonaws.com/adrf-base-jupyter"
  },
  "remote_desktop": {
    "memory": 1000,
    "cpu": 1,
    "image": "774391758379.dkr.ecr.us-gov-west-1.amazonaws.com/adrf-desktop"
  }
}
                }
```

The image information does not have the tag property. The system will always try to use the latest tag since ADRF is supposed to keep the images up to date. It means that very often ADRF will patch the images and provide a new updated image. All the users should use the most recent and updated image.

In order to call this API a user needs to be authenticated. We will create a user only for the jupyterhub service. For now we don't have it. But if you want to get token from keycloak, here is the CURL command:

Staging and DEV (You need to be in a Dev Machine):

```
export ACCESS_TOKEN=$(curl -X POST \
  https://id.adrf.info/auth/realms/ADRF/protocol/openid-connect/token \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'cache-control: no-cache'   -d 'username=<username>&password=<password>&client_id=dfadmin&grant_type=password&totp=<MFA_OTP>' | jq -r .access_token)
```

From this call, you need to get the access_token and use in the following call

```
curl -vvv -X GET \
  https://dfadmin.adrf.info/api/v1/projects/?member=<username> \
 -H 'Accept: */*'   -H "Authorization: Bearer $ACCESS_TOKEN" \
  -H 'Cache-Control: no-cache'   -H 'Connection: keep-alive' \
  -H 'Host: dfadmin.adrf.info' \
  -H 'accept-encoding: gzip, deflate' \
  -H 'cache-control: no-cache' | jq .
```

The new Jupyterhub image, handling the workspace life cycle will get all the information about the projects of a user from this last API.

**Comment by joaolrferreira** [comment]
Two pending items from original list:
- We should try to use the newest version of Z2JH
- Python Boto3 lib should be installed in the requirements.txt, and when a workspace starts and finishes, an event should be published to an AWS SNS topic **_(In progress)_**

**Comment by joaolrferreira** [comment]
There is one pending item from original list:

- We should try to use the newest version of Z2JH
